### ISSUE TITLE
Bug: Moving streams in "Additional streams" causes application crash

### ISSUE THREAD

**Issue by johnhelt** [SenexCrenshaw/StreamMaster#177]
**Describe the Bug**
When you try to prioritize the streams in the "Additional streams" menu by drag-dropping, the application throws an error: 
![image](https://github.com/SenexCrenshaw/StreamMaster/assets/43775572/db6f3319-24ba-4956-8e11-08f07b0a1e01)

**Stream Master Info**
- 0.3.2.0

**Link to logs (required)**
log part shown below
```
System.Text.Json.JsonException: A possible object cycle was detected. This can either be due to a cycle or if the object depth is larger than the maximum allowed depth of 64. Consider using ReferenceHandler.Preserve on JsonSerializerOptions to support cycles. Path: $.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.ChildVideoStreams.MaxStreams.
streammaster  | 2023-11-17T20:38:46.573926038Z          at System.Text.Json.ThrowHelper.ThrowJsonException_SerializerCycleDetected(Int32 maxDepth)
streammaster  | 2023-11-17T20:38:46.573927389Z          at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
streammaster  | 2023-11-17T20:38:46.573929421Z          at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
streammaster  | 2023-11-17T20:38:46.573930829Z          at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
streammaster  | 2023-11-17T20:38:46.573939225Z          at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)

```

**Comment by SenexCrenshaw** [comment]
Check latest
