### ISSUE TITLE
Bug: Additional Streams screen errors out

### ISSUE THREAD

**Issue by Austin1** [SenexCrenshaw/StreamMaster#179]
**Describe the Bug**
If you click edit on a channel, then select Additional Streams, then on left listbox, search something like NBC. Add 4 channels. Try to drag to re-order channels and it errors out

**Stream Master Info**
- Version Number

**Link to logs (required)**
```
Unexpected Application Error!
Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at AC (http://192.168.1.2:7095/assets/index-183e296a.js:535:19339)
    at Object.W6 [as useCallback] (http://192.168.1.2:7095/assets/index-183e296a.js:535:23763)
    at pn.useCallback (http://192.168.1.2:7095/assets/index-183e296a.js:9:5642)
    at l8 (http://192.168.1.2:7095/assets/index-183e296a.js:2081:5574)
    at NC (http://192.168.1.2:7095/assets/index-183e296a.js:535:19538)
    at Y1 (http://192.168.1.2:7095/assets/index-183e296a.js:537:3139)
    at rR (http://192.168.1.2:7095/assets/index-183e296a.js:537:2351)
    at xR (http://192.168.1.2:7095/assets/index-183e296a.js:537:47377)
    at SR (http://192.168.1.2:7095/assets/index-183e296a.js:537:39787)
    at ML (http://192.168.1.2:7095/assets/index-183e296a.js:537:39715)
```

**Comment by aniel300** [comment]
did u try clearing out browser cache?
