### ISSUE TITLE
Bug: AutoSetSMChannelNumbersFromParameters failed

### ISSUE THREAD

**Issue by infosecmatters2021** [SenexCrenshaw/StreamMaster#241]
Click Set (all) #s 
Click green check mark - All: overwrite Starting #: 1
Error appears: AutoSetSMChannelNumbersFromParameters failed

**Stream Master Info**
- 0.15.0.35
[streammaster_logs.txt](https://github.com/user-attachments/files/16661133/streammaster_logs.txt)

Excerpt:
fail: Microsoft.AspNetCore.SignalR.Internal.DefaultHubDispatcher[8]
      Failed to invoke hub method 'AutoSetSMChannelNumbersFromParameters'.
      System.InvalidOperationException: The instance of entity type 'SMStream' cannot be tracked because another instance with the key value '{Id: aHR0cHM6Ly90dm5vdy5iZXN0L2FwaS9zdHJlYW0vb2Jlcm9uLmJsb29tcXVpc3RAc2hhdy5jYS83NjQ2NjgvbGl2ZXR2LmVwZy9kaXNjb3ZlcnkuaGlzdG9yeS51ay5tM3U4}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey, Nullable`1 fallbackState)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
         at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
         at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityState(InternalEntityEntry entry, EntityState entityState)
         at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Update(TEntity entity)
         at StreamMaster.Infrastructure.EF.Repositories.SMChannelsRepository.AutoSetSMChannelNumbers(IQueryable`1 smChannels, Int32 StartingNumber, Boolean OverwriteExisting) in /src/StreamMaster.Infrastructure.EF/Repositories/SMChannelsRepository.cs:line 357
         at StreamMaster.Infrastructure.EF.Repositories.SMChannelsRepository.AutoSetSMChannelNumbersFromParameters(Int32 streamGroupId, QueryStringParameters Parameters, Nullable`1 StartingNumber, Nullable`1 OverwriteExisting) in /src/StreamMaster.Infrastructure.EF/Repositories/SMChannelsRepository.cs:line 328
         at StreamMaster.Application.SMChannels.Commands.AutoSetSMChannelNumbersFromParametersRequestHandler.Handle(AutoSetSMChannelNumbersFromParametersRequest request, CancellationToken cancellationToken) in /src/StreamMaster.Application/SMChannels/Commands/AutoSetSMChannelNumbersFromParametersRequest.cs:line 12
         at StreamMaster.Application.Hubs.StreamMasterHub.AutoSetSMChannelNumbersFromParameters(AutoSetSMChannelNumbersFromParametersRequest request) in /src/StreamMaster.Application/SMChannels/ControllerAndHub.cs:line 306

**Comment by infosecmatters2021** [comment]
It may have been due to a duplicate in my list. I haven't experienced this issue since removing that channel.

**Comment by rclarsfull** [comment]
thx helped a lot
