### ISSUE TITLE
Bug: Plex HTPC for Mac not working

### ISSUE THREAD

**Issue by fcisler** [SenexCrenshaw/StreamMaster#295]
**Describe the Bug**
Plex HTPC for Mac version 1.68.2.259-3095e860
Plex Live TV works fine on every other device I have which includes samsung, LG, roku native TV apps, FireTV's of a few generations, android app etc - except Plex HTPC. Previous threadfin and xteve instances worked and work if I switch back

**Stream Master Info**
- Version Number 0.17.9.0

**Link to logs (required)**
- https://gist.github.com/fcisler/e327107e31cac8aa02a85ac748420c39
```
fail: StreamMaster.Streams.Clients.ClientReadStream[0]
      Error reading data for UniqueRequestId: 0HN8U1UQ2UC4D:00000001
      System.OperationCanceledException: The operation was canceled.
         at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
         at StreamMaster.Streams.Clients.ClientReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken) in /src/StreamMaster.Streams/Clients/ClientReadStream.cs:line 244
```
Is from docker logs and I believe I have seen similar errors in gist above

**Comment by jia-dai** [comment]
Same on Windows  when playing Plex live TV with Chrome

**Comment by fcisler** [comment]
Can confirm FireFox on OS X works
